const a = 232;

try {
    error("AAAAAAAAAAA");
    throw a;
}
catch(err) {
    error(err);
}

print("I'M OK!");